/*
 * Standalone UI audit script. Run with:
 *   npx tsx scripts/audit-ui.ts
 *
 * Requires tests/.auth/admin.json (generated by `npm run test:e2e:auth`).
 * Visits every top-level route, captures a full-page screenshot, collects
 * console errors and failed network requests, and writes a JSON findings
 * report to audit-out/.
 *
 * BASE_URL env var overrides the default (http://localhost:5000).
 */

import { chromium } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const BASE_URL = process.env.BASE_URL || 'http://localhost:5000'
const AUTH_FILE = 'tests/.auth/admin.json'
const OUT_DIR = 'audit-out'

const ROUTES = [
  '/dashboard',
  '/pipeline',
  '/quote-sheet',
  '/master-list',
  '/cost-tracking',
  '/property-list',
  '/contacts',
  '/inspections',
  '/issues',
  '/tasks',
  '/access-codes',
  '/linen-tracker',
  '/linen-inventory',
  '/ac-filters',
  '/revenue-report',
  '/financial-dashboard',
  '/pro-forma',
  '/activity',
  '/settings',
  '/cleaners',
  '/cleaner-metrics',
  '/alerts',
  '/previous-properties',
]

interface RouteFinding {
  route: string
  status: 'ok' | 'error'
  loadTimeMs: number
  consoleErrors: string[]
  networkFailures: { url: string; status: number }[]
  pageErrors: string[]
  screenshotPath: string
}

async function main() {
  if (!fs.existsSync(AUTH_FILE)) {
    console.error(`Missing ${AUTH_FILE} — run 'npm run test:e2e:auth' first.`)
    process.exit(1)
  }
  fs.mkdirSync(OUT_DIR, { recursive: true })

  const browser = await chromium.launch({ headless: true })
  const context = await browser.newContext({
    storageState: AUTH_FILE,
    viewport: { width: 1440, height: 900 },
  })

  const findings: RouteFinding[] = []

  for (const route of ROUTES) {
    const page = await context.newPage()
    const consoleErrors: string[] = []
    const pageErrors: string[] = []
    const networkFailures: { url: string; status: number }[] = []

    page.on('console', msg => {
      if (msg.type() === 'error') consoleErrors.push(msg.text())
    })
    page.on('pageerror', err => pageErrors.push(err.message))
    page.on('response', resp => {
      if (resp.status() >= 400) {
        networkFailures.push({ url: resp.url(), status: resp.status() })
      }
    })

    const start = Date.now()
    let status: 'ok' | 'error' = 'ok'
    const screenshotPath = path.join(OUT_DIR, `${route.replace(/\//g, '_') || 'root'}.png`)
    try {
      await page.goto(`${BASE_URL}/#${route}`, { waitUntil: 'networkidle', timeout: 30_000 })
      await page.waitForTimeout(1500)
      await page.screenshot({ path: screenshotPath, fullPage: true })
    } catch (e: any) {
      status = 'error'
      pageErrors.push(`navigation: ${e.message}`)
    }
    const loadTimeMs = Date.now() - start

    findings.push({
      route,
      status,
      loadTimeMs,
      consoleErrors: consoleErrors.slice(0, 20),
      networkFailures: networkFailures.slice(0, 20),
      pageErrors: pageErrors.slice(0, 10),
      screenshotPath,
    })
    console.log(`  ${status === 'ok' ? 'OK' : 'FAIL'} ${route} — ${loadTimeMs}ms — ${consoleErrors.length} console errors, ${networkFailures.length} network fails`)
    await page.close()
  }

  fs.writeFileSync(path.join(OUT_DIR, 'findings.json'), JSON.stringify(findings, null, 2))
  console.log(`\nWrote ${findings.length} findings to ${OUT_DIR}/findings.json`)
  console.log(`Screenshots in ${OUT_DIR}/`)

  await browser.close()
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
